### ISSUE TITLE
GPT的回复无法刷新在页面，报argument of type 'NoneType' is not iterable错误。

### ISSUE THREAD

**Issue by OYLFLMH** [WongSaang/chatgpt-ui#136]
![5](https://user-images.githubusercontent.com/95945448/230770954-9f385e2d-81a2-4b45-9bca-ee7ea691eab9.jpg)
![6](https://user-images.githubusercontent.com/95945448/230770960-d63c0a4f-0515-43cc-91c6-89c8ac9d0301.jpg)
![7](https://user-images.githubusercontent.com/95945448/230770963-536c014b-2632-44af-ad77-1ba9804122a4.jpg)
![8](https://user-images.githubusercontent.com/95945448/230770967-d0ab6edb-c974-43bc-8bb8-bf72a0db4794.jpg)
昨天都一切正常，我全部重启了机器和重新部署还是一样。

**Comment by OYLFLMH** [comment]
在9000/admin 可以看到GPT 的回复，但是页面看不到，报错，如果刷新可以看到已经多了几个会话，但是我只发出一个会话问题。

**Comment by WongSaang** [comment]
你好，把 wsgi-server 打开 DEBUG 模式打开再看看日志。

```
backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - DEBUT='True'
```

**Comment by OYLFLMH** [comment]
确定qian前端WEB页面不刷新GPT的回答，后台却有N多回答。 截图如下，日志如何提取？
![44](https://user-images.githubusercontent.com/95945448/230841035-3272d9f0-c0ce-4553-a2b3-819984d2db82.jpg)
![33](https://user-images.githubusercontent.com/95945448/230841064-0da5fc90-624e-431d-a4af-d3cc2abcf999.jpg)

**Comment by OYLFLMH** [comment]
```
backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - DEBUT='True'
```
已经设置，如何提取日志?
