### ISSUE TITLE
Can't add database

### ISSUE THREAD

**Issue by BramSuurdje** [WongSaang/chatgpt-ui#146]
hi, first off just wanted to say that I really like your project!. but I have 1 issue. when I'm trying to add a database. I constantly get a Server error. I don't really understand the documentation on adding a database. if you could guide me in the right direction on how to add a database then that would be nice. here's the docker-compose I have right now

```
version: '3'
services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - NUXT_PUBLIC_APP_NAME='Brams ChatGPT' # The name of the application
#      - NUXT_PUBLIC_TYPEWRITER=true # Whether to enable the typewriter effect, default false
#      - NUXT_PUBLIC_TYPEWRITER_DELAY=50 # The delay time of the typewriter effect, default 50ms
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-82}:80'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-wsgi-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-192.168.178.4:9000}
      - SERVER_WORKERS=3
      - WORKER_TIMEOUT=180
      - DB_URL=mysql://chatgpt:$password@localhost:3306/chatgpt 
      - DJANGO_SUPERUSER_USERNAME=admin 
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none}
    ports:
      - '${WSGI_PORT:-8001}:8000'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-web-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chatgpt'
      MYSQL_USER: 'chatgpt'
      MYSQL_PASSWORD: '$password'
      MYSQL_ROOT_PASSWORD: '$password'
    networks:
      - chatgpt_ui_network
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

networks:
  chatgpt_ui_network:
    driver: bridge
```

**Comment by WongSaang** [comment]
Hello,

In a Docker container, "localhost" refers to the container itself, not the host machine. Therefore, if an application within the container needs to access a service on the host machine, it needs to use the host machine's IP address or the special DNS name "host.docker.internal" provided by Docker.

For example, if a web server is running on the host machine and listening on port 80, it can be accessed from within a container using "http://host.docker.internal:80".

Enjoy!

**Comment by WongSaang** [comment]
In a Docker container, "localhost" refers to the container itself, not the host machine. Therefore, if an application within the container needs to access a service on the host machine, it needs to use the host machine's IP address or the special DNS name "host.docker.internal" provided by Docker.

Therefore, it is recommended that you modify the database url to:

```
DB_URL=mysql://chatgpt:$password@host.docker.internal:3306/chatgpt
```

Good luck to you!

**Comment by BramSuurdje** [comment]
hmm, I have been trying to find a solution for a couple of days now. but I just cant seem to figure it out. 

wouldn't it be a good idea to create a docker-compose file with a database already connected. if you, or someone else already has one. please feel free to share them with me. because id love to use your project to share with my family and friends. but I just cant seem to adjust it for my needs

**Comment by WongSaang** [comment]
Can you successfully log in to the admin panel?

**Comment by idonda** [comment]
no, it does not login because it does not find any table, so I switched back to sqlite with persistent config.
The mysql database is initialised at startup?

**Comment by BramSuurdje** [comment]
i was able to get it to go past the 500 (server error) with a connected database by using the following docker-compose configuration.  but i cant seem to do anything in the UI of login screen. everytime i tried doing something. i got an error. any idea on how to fix or debug this problem?
![image](https://user-images.githubusercontent.com/78373894/233694269-5cab4fd5-a334-46ae-af0e-7581c7bb0fbb.png)
````yaml
version: '3'
services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - DEFAULT_LOCALE=en
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always

  backend-wsgi-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-wsgi-server:v2.3.8
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
      - SERVER_WORKERS=3
      - DB_URL=postgres://postgres:postgrespw@db/chatgpt
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none}
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=<your email>
      - EMAIL_HOST_PASSWORD=<your email password>
      - EMAIL_USE_TLS=True
      - EMAIL_FROM=no-reply@example.com
    ports:
      - '${WSGI_PORT:-8001}:8000'
    networks:
      - chatgpt_ui_network
    depends_on:
      - db
    restart: always

    backend-web-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8001
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=chatgpt
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - chatgpt_ui_network
    restart: always

volumes:
  db_data:

networks:
  chatgpt_ui_network:
    driver: bridge
```

**Comment by BramSuurdje** [comment]
i got past the 500 (Server Error) with a connected database by using the following docker compose file. but everytime i try signing up. or logging in. i get an error. is there anyway i can debug the problem?
![image](https://user-images.githubusercontent.com/78373894/233694550-496558ea-0891-46f1-9b2d-2127ff40f0f2.png)

```yaml
version: '3'
services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - DEFAULT_LOCALE=en
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always

  backend-wsgi-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-wsgi-server:v2.3.8
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
      - SERVER_WORKERS=3
      - DB_URL=postgres://postgres:postgrespw@db/chatgpt
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none}
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=<your email>
      - EMAIL_HOST_PASSWORD=<your email password>
      - EMAIL_USE_TLS=True
      - EMAIL_FROM=no-reply@example.com
    ports:
      - '${WSGI_PORT:-8001}:8000'
    networks:
      - chatgpt_ui_network
    depends_on:
      - db
    restart: always

    backend-web-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8001
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=chatgpt
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - chatgpt_ui_network
    restart: always

volumes:
  db_data:

networks:
  chatgpt_ui_network:
    driver: bridge
```
