### ISSUE TITLE
用脚本命令安装的时候最后提示“service "backend-wsgi-server" refers to undefined volume db_sqlite3: invalid compose project”

### ISSUE THREAD

**Issue by xcsyj** [WongSaang/chatgpt-ui#229]
用一键脚本在安装的最后提示：
Starting services...
touch: cannot touch './db_sqlite3/db.sqlite3': No such file or directory
service "backend-wsgi-server" refers to undefined volume db_sqlite3: invalid compose project
Done
在Ubuntu 20 LTS和Ubuntu 22 LTS 上安装的时候都会提示，这是怎么回事？

**Comment by ilovefreesw** [comment]
Replace version:'3' with the following to fix this....

```
version: '3'
volumes:
    db_sqlite3:
      driver: local
```
