### ISSUE TITLE
Docker compose - include volumes required for persistent setup?

### ISSUE THREAD

**Issue by q20** [WongSaang/chatgpt-ui#29]
Hey there

Could docker-compose.yml be updated to include all volumes required to make the setup persistent? Specifically, the standard Sqlite configuration.

Thanks!

**Comment by WongSaang** [comment]
Hello, thank you for your feedback.

I'll answer your question here first.

If you want to persist Sqlite, the path of the sqlite file inside the container is `/app/db.sqlite3`. You can use volumes in the wsgi service configured in docker-compose to map the file, for example: 

```
backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    volumes:
      - db.sqlite3:db.sqlite3
```

If you are using Mysql or PostgreSQL, you only need to configure the `DB_URL` environment variable.

**Comment by q20** [comment]
That's excellent - thank you! With that info I'll now happily test it out.  ; )

**Comment by spencerwongfeilong** [comment]
i cant get it to persist with 

    volumes:
      - /path/to/host/db.sqlite3:db.sqlite3
  
Im using  postgres DB to persist the everchanging db. 
I am still interested to make ur sqlite3 db work. Any sample of ur docker compose to make the persist of sqlite3 db work?

**Comment by q20** [comment]
Here's a snippet of my docker-compose.yml file:


```
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
    volumes:
      - /volume1/docker/chatpgpt-ui/db.sqlite3:/app/db.sqlite3
    ports:
      - '8000:8000'
```

**Comment by spencerwongfeilong** [comment]
> Here's a snippet of my docker-compose.yml file:
> 
> ```
> #      - EMAIL_HOST_PASSWORD=
> #      - EMAIL_USE_TLS=True
>     volumes:
>       - /volume1/docker/chatpgpt-ui/db.sqlite3:/app/db.sqlite3
>     ports:
>       - '8000:8000'
> ```
> 
> Of course, I had to create the file first:
> 
> `/volume1/docker/chatpgpt-ui$ touch db.sqlite3`

i try it again! thanks

**Comment by GOvEy1nw** [comment]
I'm struggling with this, when I add the volume I then get 'server error (500) when I visit the 9000/admin page. I even added the PUID/PGID values to test too, but still doesn't work. Here's my full docker-compose, am I doing something wrong?

```
version: '3'
services:
  client:
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - NUXT_PUBLIC_APP_NAME='ChatGPT UI'
      - NUXT_PUBLIC_TYPEWRITER=true # Enable typewriter effect, default is false
      - NUXT_PUBLIC_TYPEWRITER_DELAY=100 # Typewriter effect delay time, default is 50ms
    depends_on:
      - backend-web-server
    ports:
      - '8800:80'
    networks:
      - chatgpt_ui_network
  backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-192.168.1.4:9000} # CSRF whitelistï¼ŒAdd the address of your chatgpt-ui-web-server here, default is localhost:9000
      #- DB_URL=postgres://postgres:postgrespw@localhost:49153/chatgpt # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      #- OPENAI_API_PROXY=https://openai.proxy.com/v1 # Proxy for https://api.openai.com/v1
      - DJANGO_SUPERUSER_USERNAME=admin_rGXoWyqnqNU3sBxf0Bjd # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=gVFbzQB9LoXRnlxu2sOx # default superuser password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com # default superuser email
      - PUID=1026
      - PGID=100
      # If you want to use the email verification function, you need to configure the following parameters
    #      - EMAIL_HOST=SMTP server address
    #      - EMAIL_PORT=SMTP server port
    #      - EMAIL_HOST_USER=
    #      - EMAIL_HOST_PASSWORD=
    #      - EMAIL_USE_TLS=True
    volumes:
      - /volume2/docker/ChatGPT/db:/app/db.sqlite3
    ports:
      - '8000:8000'
    networks:
      - chatgpt_ui_network
  backend-web-server:
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '9000:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network

networks:
  chatgpt_ui_network:
    driver: bridge
    ```

**Comment by FarisHijazi** [comment]
@WongSaang Hello and thank you for making this amazing tool

I've been struggling the past week to get the persistent database to work, but no success.

Could you please show me a docker compose file that will work with a persistent database, it would really save me and a lot of people a lot of time.

I've tried with using volumes for the WSGI server and also tried adding a postgres DB and setting DB_URL, no success

here is my current attempt for the docker-compose.yaml:

```yaml
version: '3'
services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - DEFAULT_LOCALE=en
#      - NUXT_PUBLIC_APP_NAME='ChatGPT UI' # The name of the application
#      - NUXT_PUBLIC_TYPEWRITER=true # Whether to enable the typewriter effect, default false
#      - NUXT_PUBLIC_TYPEWRITER_DELAY=50 # The delay time of the typewriter effect, default 50ms
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-wsgi-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - DEBUG=${DEBUG:-False} # Whether to enable debug mode, default False
      - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
      - SERVER_WORKERS=3 # The number of worker processes for handling requests.
      - WORKER_TIMEOUT=180 # Workers silent for more than this many seconds are killed and restarted. default 180s
      - DB_URL=${DB_URL:-sqlite:///db.sqlite3} # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      - DJANGO_SUPERUSER_USERNAME=admin # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=password # default superuser password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com # default superuser email
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      # If you want to use the email verification function, you need to configure the following parameters
#      - EMAIL_HOST=SMTP server address
#      - EMAIL_PORT=SMTP server port
#      - EMAIL_HOST_USER=
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
#      - EMAIL_FROM=no-reply@example.com  #Default sender email address
    volumes:
      - db_sqlite3:/app/db.sqlite3
    ports:
      - '${WSGI_PORT:-8000}:8000'
    networks:
      - chatgpt_ui_network
    restart: always
  backend-web-server:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always

networks:
  chatgpt_ui_network:
    driver: bridge

volumes:
  db_sqlite3:

```


the error I get is:

```
client_1               | Listening http://[::]:80
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 167, in get_new_connection
backend-wsgi-server_1  |     conn = Database.connect(**conn_params)
backend-wsgi-server_1  | sqlite3.OperationalError: unable to open database file
backend-wsgi-server_1  | 
backend-wsgi-server_1  | The above exception was the direct cause of the following exception:
backend-wsgi-server_1  | 
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/app/manage.py", line 22, in <module>
backend-wsgi-server_1  |     main()
backend-wsgi-server_1  |   File "/app/manage.py", line 18, in main
backend-wsgi-server_1  |     execute_from_command_line(sys.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
backend-wsgi-server_1  |     utility.execute()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
backend-wsgi-server_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
backend-wsgi-server_1  |     self.execute(*args, **cmd_options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
backend-wsgi-server_1  |     return super().execute(*args, **options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 447, in execute
backend-wsgi-server_1  |     self.check_migrations()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 564, in check_migrations
backend-wsgi-server_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
backend-wsgi-server_1  |     self.loader = MigrationLoader(self.connection)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
backend-wsgi-server_1  |     self.build_graph()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
backend-wsgi-server_1  |     self.applied_migrations = recorder.applied_migrations()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
backend-wsgi-server_1  |     if self.has_table():
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
backend-wsgi-server_1  |     with self.connection.cursor() as cursor:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
backend-wsgi-server_1  |     return self._cursor()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
backend-wsgi-server_1  |     self.ensure_connection()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
backend-wsgi-server_1  |     with self.wrap_database_errors:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
backend-wsgi-server_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 167, in get_new_connection
backend-wsgi-server_1  |     conn = Database.connect(**conn_params)
backend-wsgi-server_1  | django.db.utils.OperationalError: unable to open database file
backend-wsgi-server_1  | [2023-05-01 12:21:21 +0000] [1] [INFO] Starting gunicorn 20.1.0
```
