### ISSUE TITLE
/admin 404, page not found

### ISSUE THREAD

**Issue by q20** [WongSaang/chatgpt-ui#30]
Hello again!

Using the following YML for docker compose, all looks well, yet I am unable to open the admin page, instead getting a 404. Is there anything wrong with the changes I have made to the default configuration?

`
`version: '3'
services:
  client:
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=https://chatgpt.MYDOMAIN.COM
      - NUXT_PUBLIC_APP_NAME='ChatGPT UI'
      - NUXT_PUBLIC_TYPEWRITER=true
      - NUXT_PUBLIC_TYPEWRITER_DELAY=100
    depends_on:
      - backend-web-server
    ports:
      - '2480:80'
    networks:
      - chatgpt_ui_network
  backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      - APP_DOMAIN=127.0.0.1:2428
      #      - DB_URL=postgres://postgres:postgrespw@localhost:49153/chatgpt # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      - DJANGO_SUPERUSER_USERNAME=admin # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=password # default superuser password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com # default superuser email
      # If you want to use the email verification function, you need to configure the following parameters
#      - EMAIL_HOST=SMTP server address
#      - EMAIL_PORT=SMTP server port
#      - EMAIL_HOST_USER=
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
    volumes:
      - /volume1/docker/chatpgpt-ui/db.sqlite3:/app/db.sqlite3
    ports:
      - '8000:8000'
    networks:
      - chatgpt_ui_network
  backend-web-server:
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://127.0.0.1:8000
    ports:
      - '2428:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network

networks:
  chatgpt_ui_network:
    driver: bridge``

I made a couple of changes as ports 80 and 9000 are unavailable/already in use. Changes to 2480 and 2428

Thanks! : )

**Comment by WongSaang** [comment]
Please note that `127.0.0.1` points to the container's internal address. I suggest using the following address.

```
backend-web-server:
    image: wongsaang/chatgpt-ui-web-server:latest
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
```

**Comment by WongSaang** [comment]
Another solution could be referenced at:

https://github.com/WongSaang/chatgpt-ui/issues/27#issuecomment-1464924770

**Comment by q20** [comment]
Thanks for the suggestion. I have now specified the IP on the host running docker, recreated the containers, and still 404 trying to access /admin.
Any other ideas?

**Comment by spencerwongfeilong** [comment]
try this       

- APP_DOMAIN=https://your-host-address:2428

**Comment by WongSaang** [comment]
Can you please send the complete content of your compose.yml file again?

**Comment by q20** [comment]
No problem. Here it is:


```
version: '3'
services:
  client:
    image: wongsaang/chatgpt-ui-client:latest
    restart: always
    environment:
      - SERVER_DOMAIN=https://MYDOMAIN.COM
      - NUXT_PUBLIC_APP_NAME='ChatGPT UI'
      - NUXT_PUBLIC_TYPEWRITER=true
      - NUXT_PUBLIC_TYPEWRITER_DELAY=100
    depends_on:
      - backend-web-server
    ports:
      - '2480:80'
    networks:
      - chatgpt_ui_network
  backend-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    restart: always
    environment:
      - APP_DOMAIN=HOSTIP:2428
      #      - DB_URL=postgres://postgres:postgrespw@localhost:49153/chatgpt # If this parameter is not set, the built-in Sqlite will be used by default. It should be noted that if you do not connect to an external database, the data will be lost after the container is destroyed.
      - DJANGO_SUPERUSER_USERNAME=admin # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=password # default superuser password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com # default superuser email
      # If you want to use the email verification function, you need to configure the following parameters
#      - EMAIL_HOST=SMTP server address
#      - EMAIL_PORT=SMTP server port
#      - EMAIL_HOST_USER=
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
    volumes:
      - /volume1/docker/chatpgpt-ui/db.sqlite3:/app/db.sqlite3
    ports:
      - '8000:8000'
    networks:
      - chatgpt_ui_network
  backend-web-server:
    image: wongsaang/chatgpt-ui-web-server:latest
    restart: always
    environment:
      - BACKEND_URL=http://HOSTIP:8000
    ports:
      - '2428:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network

networks:
  chatgpt_ui_network:
    driver: bridge
```


I'm no Docker expert, but could my issue lie with all the port changes? Perhaps you could use "expose" to allow the containers to communicate with each other on the default without interfering with the Docker host's ports? We could then specify a single port forward for the web client (in my case, 2480:80).
